#!/bin/bash

# A pre-commit hook that makes it illegal to commit to master
# on the repo.  An exception is made for 'arc', which is the preffered
# workflow.
#
# For emergencies, you can override this hook prefixing your command with
# a `NOHOOK=1` environment variable, e.g.:
#
#     NOHOOK=1 git commit -m "yoloswag420"

# 'arc' will set this ARCANIST environment variable while it runs a command
#
# $NOHOOK allows skipping of all hooks including prepare-commit-msg, which
# does not support skipping via the --no-verify flag, unfortunately.
if [ -n "$ARCANIST" ] || [ -n "$NOHOOK" ]; then
    exit 0
fi

if [ "$(git rev-parse --abbrev-ref HEAD)" = "master" ]; then
    RED=`tput setaf 1`
    BLUE=`tput setaf 4`
    UL=`tput smul`
    RESET=`tput sgr0`

    echo -e "${RED}FATAL ERROR: You cannot commit directly to the master branch."
    echo
    echo -e "${BLUE}Commit to a feature branch instead:"
    echo -e "    > ${UL}http://git.io/phab-at-bp"
    echo -en ${RESET}

    unset RED BLUE UL RESET
    exit 1
fi
