#!/bin/sh

# A pre-push hook that makes it illegal to push to master on the remote.  An
# exception is made for 'arc land', which is the preffered workflow.
#
# For emergencies, you can override this hook by using 'git push --no-verify'.

# 'arc' will set this ARCANIST environment variable while it runs a command
if [ "$ARCANIST" = "land" ]; then
    exit 0
fi

# Each line has the format
#    <local ref> <sha> <remote ref> <sha>
# We complain if any remote ref is refs/heads/master
while read local_ref local_sha remote_ref remote_sha; do
    if [ "$remote_ref" = "refs/heads/master" ]; then
        echo "FATAL ERROR: You cannot push to the master branch on github."
        echo
        echo "Instead, you must deploy a feature branch via 'arc land'."
        echo "    https://docs.calblueprint.org/dev/git-at-bp"
        exit 1
    fi
done
