#!/bin/bash

# A prepare-commit-message hook that makes it illegal to commit using the '-m'
# flag. Developers should commit normally or use '--amend' instead, in order
# to pick up the commit template. An exception is made for 'arc', which
# is the preferred workflow.
#
# For emergencies, you can override this hook prefixing your command with
# a `NOHOOK=1` environment variable, e.g.:
#
#     NOHOOK=1 git commit -m "yoloswag420"

# 'arc' will set this ARCANIST environment variable while it runs a command
#
# $NOHOOK allows skipping of all hooks including prepare-commit-msg, which
# does not support skipping via the --no-verify flag, unfortunately.
if [ -n "$ARCANIST" ] || [ -n "$NOHOOK" ]; then
    exit 0
fi

if [ "$2" = "message" ]; then
    echo -e "\033[0;31mFATAL ERROR: Cannot commit with the '-m' flag."
    echo
    echo -e "\033[34mIf you're fixing an existing diff, use the \033[35m--amend\033[34m flag."
    echo -e "If you plan to amend and do not want to change your message,"
    echo -e "use \033[35m--no-edit\033[34m as well."
    echo -e "    > \033[4mhttp://docs.calblueprint.org/dev/phab-at-bp\033[0m"
    exit 1
fi
